'''
This file contains all the constants
'''

STR_UNDEFINED = 'Undefined'

'''
Below fields are related to Google Drive API
'''
CLIENTSECRET_LOCATION = '/Users/shivankurkapoor/PycharmProjects/BioinformaticsPipeline/application/auth/client_secret.json'
REDIRECT_URI = 'postmessage'
SCOPES = [
    'https://www.googleapis.com/auth/drive.file'
    # Add other requested scopes.
]
ORIGIN = 'http://localhost:5000'


'''
This is the Application secret key of our application.
This is not generated by Google or any third-party API
'''
APP_SECRET_KEY = 'BioInfo:AQWER-WDSEE-DDEWE-WECEG8'


'''
Renew Token URI
'''
RENEW_TOKEN_URL = 'accounts.google.com'
RENEW_TOKEN_PATH = '/o/oauth2/token'
RENEW_TOKEN_PARAMS = 'client_id={client_id}&client_secret={client_secret}&refresh_token={refresh_token}&grant_type={grant_type}'

'''
GOOGLE DRIVE FILE DOWNLOAD
'''
DOWNLOAD_FILE_URL = 'googleapis.com/drive/v2/files/{fileId}?alt=media'

'''
Error Codes for various purpose
'''
INT_ERROR_GENERAL = -1000
INT_ERROR_NOTEXIST = -3000
INT_ERROR_FOUND = -3001
INT_ERROR_PASSEDEXPTIME = -2000
INT_ERROR_FORMAT = -4000
INT_ERROR_TIMEOUT = -4008
INT_ERROR_MAXATTEMPTREACHED = -40080
INT_FAILURE = -1001
INT_FAILURE_AUTH = -1002
INT_FAILURE_RENEW = -1003
INT_ILLEGAL_HTTPMETHOD = -4001
INT_NOTEXISTS = 3000
INT_FOUND = 3001
INT_LOGGEDOUT = 1009
INT_OK = 0
INT_CREATED = 2001
